### ISSUE TITLE
MaryConfigurationException: Cannot start MARY server

### ISSUE THREAD

**Issue by nalbion** [OpenASR/idear#31]
`MaryConfig.getMainConfig()` returns null which leads to the following stack trace:

```
marytts.exceptions.MaryConfigurationException: Cannot start MARY server
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:66)
	at com.jetbrains.idear.tts.TTSService.<init>(TTSService.kt:23)
	at com.jetbrains.idear.tts.TTSService.<clinit>(TTSService.kt:16)
	at com.jetbrains.idear.asr.ASRControlLoop.run(ASRControlLoop.kt:40)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at marytts.util.MaryRuntimeUtils.ensureMaryStarted(MaryRuntimeUtils.java:70)
	at marytts.LocalMaryInterface.<init>(LocalMaryInterface.java:64)
	... 4 more
Exception in thread "ASR Thread" kotlin.KotlinNullPointerException
	at com.jetbrains.idear.tts.TTSService.say(TTSService.kt:46)
	at com.jetbrains.idear.asr.ASRControlLoop.run(ASRControlLoop.kt:40)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by breandan** [comment]
This is caused by some bizarre classloader issue with IntelliJ Platform Plugins. [This comment](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206761975-How-to-load-classes-in-a-plugin-with-ServiceLoader-?page=1#community_comment_206111895) has the solution (I haven't the faintest clue why this works):

```
Thread.currentThread().contextClassLoader = this.javaClass.classLoader
```
