### ISSUE TITLE
Invalid security token

### ISSUE THREAD

**Issue by breandan** [OpenASR/idear#45]
Getting this error when I try to run `PollyTTS.main`. Is AWS looking for the credentials in a particularly directory (currently stored in `~/.aws/credentials`)?

```
Exception in thread "main" com.amazonaws.services.polly.model.AmazonPollyException: The security token included in the request is invalid. (Service: AmazonPolly; Status Code: 403; Error Code: UnrecognizedClientException; Request ID: bec88896-6b9d-11e7-b8a7-03e6601caa74)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.polly.AmazonPollyClient.doInvoke(AmazonPollyClient.java:742)
	at com.amazonaws.services.polly.AmazonPollyClient.invoke(AmazonPollyClient.java:718)
	at com.amazonaws.services.polly.AmazonPollyClient.executeDescribeVoices(AmazonPollyClient.java:428)
	at com.amazonaws.services.polly.AmazonPollyClient.describeVoices(AmazonPollyClient.java:404)
	at org.openasr.idear.tts.PollyTTS.<init>(PollyTTS.kt:34)
	at org.openasr.idear.tts.PollyTTSKt.main(PollyTTS.kt:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by nalbion** [comment]
No, it should not need that - it's (supposed to be) using Cognito to generate temporary credentials.

I can see that you logged in here - https://console.aws.amazon.com/cognito/identities/?region=us-east-1&pool=us-east-1:212de8d8-ca7e-4c5e-9628-382c17a50cbc

**Comment by nalbion** [comment]
using BasicSessionCredentials now

**Comment by breandan** [comment]
Thanks, works for me now.
